/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ServicoDAO;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Servico;

/**
 *
 * @author Luiz Alberto Teodoro de Arruda
 */
public class GerenciarServicos extends javax.swing.JFrame {

    private final int NOME = 0;
    private final int PRECO = 1;

    private ArrayList<Servico> servicos;
    private DefaultTableModel table;
    private boolean subList;
    private int position;

    /**
     * Creates new form VerificarReserva
     */
    public GerenciarServicos() {
        initComponents();
        servicos = new ServicoDAO().queryAll();
        subList = false;
        position = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlServicos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblProcurar = new javax.swing.JLabel();
        txtProcurar = new javax.swing.JTextField();
        bttProcurar = new javax.swing.JButton();
        lblServicos = new javax.swing.JLabel();
        scrServicos = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();
        bttCadastrar = new javax.swing.JButton();
        bttEditar = new javax.swing.JButton();
        bttExcluir = new javax.swing.JButton();
        bttVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlServicos.setBackground(new java.awt.Color(255, 255, 255));
        pnlServicos.setName("excluir"); // NOI18N
        pnlServicos.setPreferredSize(new java.awt.Dimension(400, 512));

        lblTitulo.setBackground(new java.awt.Color(102, 0, 153));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerenciar Serviços");
        lblTitulo.setOpaque(true);

        lblProcurar.setForeground(new java.awt.Color(102, 0, 153));
        lblProcurar.setText("Procurar serviço:");

        bttProcurar.setBackground(new java.awt.Color(102, 0, 153));
        bttProcurar.setForeground(new java.awt.Color(255, 255, 255));
        bttProcurar.setText("Procurar");
        bttProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProcurarActionPerformed(evt);
            }
        });

        lblServicos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblServicos.setForeground(new java.awt.Color(102, 0, 153));
        lblServicos.setText("Serviços cadastrados:");

        tblServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicosMouseClicked(evt);
            }
        });
        scrServicos.setViewportView(tblServicos);

        bttCadastrar.setBackground(new java.awt.Color(102, 0, 153));
        bttCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bttCadastrar.setText("Cadastrar");
        bttCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarActionPerformed(evt);
            }
        });

        bttEditar.setBackground(new java.awt.Color(102, 0, 153));
        bttEditar.setForeground(new java.awt.Color(255, 255, 255));
        bttEditar.setText("Editar");
        bttEditar.setEnabled(false);
        bttEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditarActionPerformed(evt);
            }
        });

        bttExcluir.setBackground(new java.awt.Color(102, 0, 153));
        bttExcluir.setForeground(new java.awt.Color(255, 255, 255));
        bttExcluir.setText("Excluir");
        bttExcluir.setEnabled(false);
        bttExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExcluirActionPerformed(evt);
            }
        });

        bttVoltar.setBackground(new java.awt.Color(255, 255, 255));
        bttVoltar.setForeground(new java.awt.Color(102, 0, 153));
        bttVoltar.setText("Voltar");
        bttVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlServicosLayout = new javax.swing.GroupLayout(pnlServicos);
        pnlServicos.setLayout(pnlServicosLayout);
        pnlServicosLayout.setHorizontalGroup(
            pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicosLayout.createSequentialGroup()
                        .addComponent(txtProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicosLayout.createSequentialGroup()
                        .addComponent(bttVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlServicosLayout.createSequentialGroup()
                        .addComponent(bttCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlServicosLayout.setVerticalGroup(
            pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicosLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProcurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblServicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCadastrar)
                    .addComponent(bttEditar))
                .addGap(18, 18, 18)
                .addGroup(pnlServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVoltar)
                    .addComponent(bttExcluir))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarActionPerformed
        ManipularServico cadastro = new ManipularServico();
        cadastro.show();

        cadastro.bttSalvar.addActionListener((ActionEvent e) -> {
            boolean unique = true;

            for (Servico s : servicos) {
                if (s.getNome().equals(cadastro.txtNome.getText())) {
                    unique = false;
                }
            }

            if (unique) {
                Servico servico = new Servico(cadastro.txtNome.getText(),
                        cadastro.txtPreco.getText());
                ServicoDAO dao = new ServicoDAO();
                servico.setId(dao.insert(servico));
                servicos.add(servico);
                table.addRow(new Object[]{servico.getNome(),
                    String.valueOf(servico.getPreco())});

                cadastro.dispose();

            } else {
                String msg = "O serviço " + cadastro.txtNome.getText()
                        + " já está cadastrado.\nImpossível cadastrar"
                        + " outro serviço com o mesmo nome.";
                JOptionPane.showMessageDialog(cadastro, msg,
                        "Serviço já cadastrado", JOptionPane.ERROR_MESSAGE);
                cadastro.txtNome.setText("");
            }
        });
    }//GEN-LAST:event_bttCadastrarActionPerformed

    private void bttEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditarActionPerformed
        Servico servico = servicos.get(position);
        ManipularServico cadastro = new ManipularServico();
        cadastro.show();
        cadastro.txtNome.setText(servico.getNome());
        cadastro.txtPreco.setText(String.valueOf(servico.getPreco()));

        cadastro.bttSalvar.addActionListener((ActionEvent e) -> {
            if (!servico.getNome().equals(cadastro.txtNome.getText())
                    || !String.valueOf(servico.getPreco())
                            .equals(cadastro.txtPreco.getText())) {
                
                boolean unique = true;
                servico.setNome(cadastro.txtNome.getText());
                servico.setPreco(cadastro.txtPreco.getText());

                for (Servico s : servicos) {
                    if (s.getNome().equals(cadastro.txtNome.getText())
                            && s.getId() != servico.getId()) {
                        unique = false;
                    }
                }

                if (unique) {
                    ServicoDAO dao = new ServicoDAO();
                    dao.update(servico);
                    servicos.set(position, servico);
                    table.setValueAt(servico.getNome(), position, NOME);
                    table.setValueAt(String.valueOf(servico.getPreco()),
                            position, PRECO);
                    cadastro.dispose();

                } else {
                    String msg = "O serviço de " + cadastro.txtNome.getText()
                            + " já está cadastrado.\nImpossível cadastrar"
                            + " outro serviço com o mesmo nome.";
                    JOptionPane.showMessageDialog(cadastro, msg,
                            "Serviço já cadastrado", JOptionPane.ERROR_MESSAGE);
                    cadastro.txtNome.setText("");
                }
            } else {
                String msg = "Não houve alteração no serviço de "
                        + cadastro.txtNome.getText() + ".";
                JOptionPane.showMessageDialog(cadastro, msg,
                        "Alteração não salva", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }//GEN-LAST:event_bttEditarActionPerformed

    private void bttExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttExcluirActionPerformed
        String msg = "Você está prestes a excluir o serviço de "
                + servicos.get(position).getNome() + "!"
                + "\nDeseja mesmo excluí-lo?";

        int res = JOptionPane.showConfirmDialog(
                rootPane, msg, "Excluindo serviço",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (res == JOptionPane.YES_OPTION) {
            ServicoDAO dao = new ServicoDAO();
            dao.delete(servicos.remove(position));
            table.removeRow(position);
            bttEditar.setEnabled(false);
            bttExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_bttExcluirActionPerformed

    private void bttProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProcurarActionPerformed
        if (txtProcurar.getText().trim().isEmpty()) {
            if (subList) {
                ServicoDAO dao = new ServicoDAO();
                servicos = dao.queryAll();
                inflateTable();
                subList = false;
            }
            txtProcurar.setText("");

        } else {
            ServicoDAO dao = new ServicoDAO();
            servicos = dao.queryForString(txtProcurar.getText());
            inflateTable();
            subList = true;
        }
    }//GEN-LAST:event_bttProcurarActionPerformed

    private void bttVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_bttVoltarActionPerformed

    private void tblServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicosMouseClicked
        position = tblServicos.getSelectedRow();

        if (position != -1) {
            bttEditar.setEnabled(true);
            bttExcluir.setEnabled(true);
        } else {
            bttEditar.setEnabled(false);
            bttExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_tblServicosMouseClicked

    protected void inflateTable() {
        String col[] = {"Nome", "Preço"};
        table = new DefaultTableModel(col, 0) {
            boolean[] canEdit = new boolean[] {false, false};

            @Override
            public boolean isCellEditable(int row, int column) {
                //return super.isCellEditable(row, column);
                return canEdit[column];
            }
        };
        tblServicos.setModel(table);

        servicos.forEach((servico) -> {
            table.addRow(new Object[] {
                servico.getNome(),
                String.valueOf(servico.getPreco())
            });
        });

        bttEditar.setEnabled(false);
        bttExcluir.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCadastrar;
    private javax.swing.JButton bttEditar;
    private javax.swing.JButton bttExcluir;
    private javax.swing.JButton bttProcurar;
    private javax.swing.JButton bttVoltar;
    private javax.swing.JLabel lblProcurar;
    private javax.swing.JLabel lblServicos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlServicos;
    private javax.swing.JScrollPane scrServicos;
    protected javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
