package view;

import dao.ClienteDAO;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author Luiz Alberto Teodoro de Arruda
 */
public class GerenciarClientes extends javax.swing.JFrame {

    private final int NOME = 0;
    private final int TELEFONE = 1;

    private ArrayList<Cliente> clientes;
    private DefaultTableModel table;
    private boolean subList;
    private int position;

    public GerenciarClientes() {
        initComponents();
        clientes = new ClienteDAO().queryAll();
        subList = false;
        position = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlClientes = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblProcurar = new javax.swing.JLabel();
        txtProcurar = new javax.swing.JTextField();
        bttProcurar = new javax.swing.JButton();
        lblClientes = new javax.swing.JLabel();
        scrClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        bttCadastrar = new javax.swing.JButton();
        bttEditar = new javax.swing.JButton();
        bttExcluir = new javax.swing.JButton();
        bttVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlClientes.setPreferredSize(new java.awt.Dimension(400, 512));

        lblTitulo.setBackground(new java.awt.Color(102, 0, 153));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerenciar Clientes");
        lblTitulo.setOpaque(true);

        lblProcurar.setForeground(new java.awt.Color(102, 0, 153));
        lblProcurar.setText("Procurar cliente:");

        bttProcurar.setBackground(new java.awt.Color(102, 0, 153));
        bttProcurar.setForeground(new java.awt.Color(255, 255, 255));
        bttProcurar.setText("Procurar");
        bttProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProcurarActionPerformed(evt);
            }
        });

        lblClientes.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(102, 0, 153));
        lblClientes.setText("Clientes cadastrados:");

        tblClientes.getTableHeader().setReorderingAllowed(false);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        scrClientes.setViewportView(tblClientes);

        bttCadastrar.setBackground(new java.awt.Color(102, 0, 153));
        bttCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bttCadastrar.setText("Cadastrar");
        bttCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCadastrarActionPerformed(evt);
            }
        });

        bttEditar.setBackground(new java.awt.Color(102, 0, 153));
        bttEditar.setForeground(new java.awt.Color(255, 255, 255));
        bttEditar.setText("Editar");
        bttEditar.setEnabled(false);
        bttEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditarActionPerformed(evt);
            }
        });

        bttExcluir.setBackground(new java.awt.Color(102, 0, 153));
        bttExcluir.setForeground(new java.awt.Color(255, 255, 255));
        bttExcluir.setText("Excluir");
        bttExcluir.setEnabled(false);
        bttExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExcluirActionPerformed(evt);
            }
        });

        bttVoltar.setBackground(new java.awt.Color(255, 255, 255));
        bttVoltar.setForeground(new java.awt.Color(102, 0, 153));
        bttVoltar.setText("Voltar");
        bttVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(txtProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblProcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(bttVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClientesLayout.createSequentialGroup()
                        .addComponent(bttCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProcurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCadastrar)
                    .addComponent(bttEditar))
                .addGap(18, 18, 18)
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVoltar)
                    .addComponent(bttExcluir))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarActionPerformed
        ManipularCliente cadastro = new ManipularCliente();
        cadastro.show();

        cadastro.bttSalvar.addActionListener((ActionEvent e) -> {
            boolean unique = true;

            for (Cliente c : clientes) {
                if (c.getTelefone().equals(cadastro.txtTelefone.getText())) {
                    unique = false;
                }
            }

            if (unique) {
                Cliente cliente = new Cliente(cadastro.txtNome.getText(),
                        cadastro.txtTelefone.getText());
                ClienteDAO dao = new ClienteDAO();
                cliente.setId(dao.insert(cliente));
                clientes.add(cliente);
                table.addRow(new Object[]{cliente.getNome(),
                    cliente.getTelefone()});

                cadastro.dispose();

            } else {
                String msg = "O número de telefone "
                        + cadastro.txtTelefone.getText()
                        + " já está cadastrado.\nImpossível cadastrar"
                        + " outro cliente com o mesmo número.";
                JOptionPane.showMessageDialog(cadastro, msg,
                        "Número já cadastrado", JOptionPane.ERROR_MESSAGE);
                cadastro.txtTelefone.setText("");
            }
        });
    }//GEN-LAST:event_bttCadastrarActionPerformed

    private void bttEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditarActionPerformed
        Cliente cliente = clientes.get(position);
        ManipularCliente cadastro = new ManipularCliente();
        cadastro.show();
        cadastro.txtNome.setText(cliente.getNome());
        cadastro.txtTelefone.setText(cliente.getTelefone());

        cadastro.bttSalvar.addActionListener((ActionEvent e) -> {
            if (!cliente.getNome().equals(cadastro.txtNome.getText())
                    || !cliente.getTelefone()
                            .equals(cadastro.txtTelefone.getText())) {

                boolean unique = true;
                cliente.setNome(cadastro.txtNome.getText());
                cliente.setTelefone(cadastro.txtTelefone.getText());

                for (Cliente c : clientes) {
                    if (c.getTelefone().equals(cadastro.txtTelefone.getText())
                            && c.getId() != cliente.getId()) {
                        unique = false;
                    }
                }

                if (unique) {
                    ClienteDAO dao = new ClienteDAO();
                    dao.update(cliente);
                    clientes.set(position, cliente);
                    table.setValueAt(cliente.getNome(), position, NOME);
                    table.setValueAt(cliente.getTelefone(), position, TELEFONE);

                    cadastro.dispose();

                } else {
                    String msg = "O número de telefone "
                            + cadastro.txtTelefone.getText()
                            + " já está cadastrado.\nImpossível cadastrar"
                            + " outro cliente com o mesmo número.";
                    JOptionPane.showMessageDialog(cadastro, msg,
                            "Número já cadastrado", JOptionPane.ERROR_MESSAGE);
                    cadastro.txtTelefone.setText("");
                }
                
            } else {
                String msg = "Não houve alteração em "
                        + cadastro.txtNome.getText() + ".";
                JOptionPane.showMessageDialog(cadastro, msg,
                        "Alteração não salva", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }//GEN-LAST:event_bttEditarActionPerformed

    private void bttExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttExcluirActionPerformed
        String msg = "Você está prestes a excluir "
                + clientes.get(position).getNome() + " de seus clientes!"
                + "\nDeseja mesmo excluí-lo?";

        int res = JOptionPane.showConfirmDialog(
                rootPane, msg, "Excluindo cliente",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (res == JOptionPane.YES_OPTION) {
            ClienteDAO dao = new ClienteDAO();
            dao.delete(clientes.remove(position));
            table.removeRow(position);
            bttEditar.setEnabled(false);
            bttExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_bttExcluirActionPerformed

    private void bttVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_bttVoltarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        position = tblClientes.getSelectedRow();

        if (position != -1) {
            bttEditar.setEnabled(true);
            bttExcluir.setEnabled(true);
        } else {
            bttEditar.setEnabled(false);
            bttExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void bttProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProcurarActionPerformed
        if (txtProcurar.getText().trim().isEmpty()) {
            if (subList) {
                ClienteDAO dao = new ClienteDAO();
                clientes = dao.queryAll();
                inflateTable();
                subList = false;
            }
            txtProcurar.setText("");

        } else {
            ClienteDAO dao = new ClienteDAO();
            clientes = dao.queryForString(txtProcurar.getText());
            inflateTable();
            subList = true;
        }
    }//GEN-LAST:event_bttProcurarActionPerformed

    protected void inflateTable() {
        String col[] = {"Nome", "Telefone"};
        table = new DefaultTableModel(col, 0) {
            boolean[] canEdit = new boolean[] {false, false};

            @Override
            public boolean isCellEditable(int row, int column) {
                //return super.isCellEditable(row, column);
                return canEdit[column];
            }
        };
        tblClientes.setModel(table);

        clientes.forEach((cliente) -> {
            table.addRow(new Object[] {
                cliente.getNome(),
                cliente.getTelefone()
            });
        });
        
        bttEditar.setEnabled(false);
        bttExcluir.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCadastrar;
    private javax.swing.JButton bttEditar;
    private javax.swing.JButton bttExcluir;
    private javax.swing.JButton bttProcurar;
    private javax.swing.JButton bttVoltar;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblProcurar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JScrollPane scrClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
