/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ClienteDAO;
import dao.FuncionarioDAO;
import dao.ServicoDAO;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Servico;
import model.Funcionario;

/**
 *
 * @author Luiz Alberto Teodoro de Arruda
 */
public class ManipularReserva extends javax.swing.JFrame {

    protected ArrayList<Cliente> clientes;
    protected ArrayList<Servico> servicos;
    protected ArrayList<Funcionario> funcionarios;
    
    /**
     * Creates new form Reserva
     */
    public ManipularReserva() {
        initComponents();
        clientes = new ClienteDAO().queryAll();
        servicos = new ServicoDAO().queryAll();
        funcionarios = new FuncionarioDAO().queryAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReserva = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        boxCliente = new javax.swing.JComboBox<>();
        lblServico = new javax.swing.JLabel();
        boxServico = new javax.swing.JComboBox<>();
        lblFuncionario = new javax.swing.JLabel();
        boxFuncionario = new javax.swing.JComboBox<>();
        lblData = new javax.swing.JLabel();
        choData = new datechooser.beans.DateChooserCombo();
        lblHorario = new javax.swing.JLabel();
        scrHorario = new javax.swing.JScrollPane();
        lstHorario = new javax.swing.JList<>();
        bttSalvar = new javax.swing.JButton();
        bttCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 575));

        pnlReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlReserva.setName("reservar"); // NOI18N
        pnlReserva.setPreferredSize(new java.awt.Dimension(400, 575));

        lblTitulo.setBackground(new java.awt.Color(102, 0, 153));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Reservar Horário");
        lblTitulo.setOpaque(true);

        lblCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(102, 0, 153));
        lblCliente.setText("Escolha o cliente:");

        boxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Serviço 1", "Serviço 2", "Serviço 3" }));
        boxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxClienteActionPerformed(evt);
            }
        });

        lblServico.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblServico.setForeground(new java.awt.Color(102, 0, 153));
        lblServico.setText("Escolha o serviço:");

        boxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Serviço 1", "Serviço 2", "Serviço 3" }));
        boxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxServicoActionPerformed(evt);
            }
        });

        lblFuncionario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFuncionario.setForeground(new java.awt.Color(102, 0, 153));
        lblFuncionario.setText("Escolha o funcionário:");
        lblFuncionario.setFocusable(false);

        boxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Funcionário 1", "Funcionário 2", "Funcionário 3" }));
        boxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFuncionarioActionPerformed(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblData.setForeground(new java.awt.Color(102, 0, 153));
        lblData.setText("Escolha a data:");
        lblData.setFocusable(false);

        choData.setLocale(new java.util.Locale("pt", "BR", ""));
        choData.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                choDataOnSelectionChange(evt);
            }
        });

        lblHorario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(102, 0, 153));
        lblHorario.setText("Escolha o horário:");
        lblHorario.setFocusable(false);

        lstHorario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstHorario.setSelectionBackground(new java.awt.Color(102, 0, 153));
        lstHorario.setSelectionForeground(new java.awt.Color(255, 255, 255));
        lstHorario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstHorarioValueChanged(evt);
            }
        });
        scrHorario.setViewportView(lstHorario);

        bttSalvar.setBackground(new java.awt.Color(102, 0, 153));
        bttSalvar.setForeground(new java.awt.Color(255, 255, 255));
        bttSalvar.setText("Reservar");

        bttCancelar.setBackground(new java.awt.Color(255, 255, 255));
        bttCancelar.setForeground(new java.awt.Color(102, 0, 153));
        bttCancelar.setText("Cancelar");
        bttCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReservaLayout = new javax.swing.GroupLayout(pnlReserva);
        pnlReserva.setLayout(pnlReservaLayout);
        pnlReservaLayout.setHorizontalGroup(
            pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservaLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlReservaLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlReservaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(bttCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boxServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        pnlReservaLayout.setVerticalGroup(
            pnlReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservaLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choData, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttCancelar)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxServicoActionPerformed
        /*if (resBoxServico.getSelectedIndex() == 0) {
            resBoxFuncionario.setEnabled(false);
            resLblFuncionario.setEnabled(false);
        } else {
            FuncionarioDAO listaFuncionario = new FuncionarioDAO();
            resBoxFuncionario.removeAllItems();
            resBoxFuncionario.addItem("");
            // Carregar funcionários que realizam o serviço selecionado
            int id = resBoxServico.getSelectedIndex()-1;
            for (String funcionario : listaFuncionario.consultarFun(id)) {
                resBoxFuncionario.addItem(funcionario);
            }
            resLblFuncionario.setEnabled(true);
            resBoxFuncionario.setEnabled(true);
        }
        resBoxFuncionario.setSelectedIndex(0);*/
    }//GEN-LAST:event_boxServicoActionPerformed

    private void boxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFuncionarioActionPerformed
        /*choData.setSelectedDate(null);

        if (boxFuncionario.getSelectedIndex() == 0) {
            choData.setEnabled(false);
            lblData.setEnabled(false);
        } else {
            lblData.setEnabled(true);
            choData.setEnabled(true);
        }*/
    }//GEN-LAST:event_boxFuncionarioActionPerformed

    private void choDataOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_choDataOnSelectionChange
        /*lstHorario.setSelectedIndex(0);

        if (choData.getSelectedDate() == null) {
            lstHorario.setVisible(false);
        } else {
            // Carregar horários vagos do funcinário na data selecionada
            //
            lstHorario.setVisible(true);
        }*/
    }//GEN-LAST:event_choDataOnSelectionChange

    private void lstHorarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstHorarioValueChanged
        /*if (lstHorario.getSelectedIndex() == 0) {
            bttSalvar.setEnabled(false);
        } else {
            bttSalvar.setEnabled(true);
        }*/
    }//GEN-LAST:event_lstHorarioValueChanged

    private void bttCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_bttCancelarActionPerformed

    private void boxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxClienteActionPerformed

    protected void inflateTable() {
        String[] c = new String[clientes.size()+1];
        c[0] = "";
        for (int i = 0; i < clientes.size(); i++) {
            c[i+1] = clientes.get(i).getNome();
        }
        boxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(c));
        
        String[] s = new String[servicos.size()+1];
        s[0] = "";
        for (int i = 0; i < servicos.size(); i++) {
            s[i+1] = servicos.get(i).getNome();
        }
        boxServico.setModel(new javax.swing.DefaultComboBoxModel<>(s));
        
        String[] f = new String[funcionarios.size()+1];
        f[0] = "";
        for (int i = 0; i < funcionarios.size(); i++) {
            f[i+1] = funcionarios.get(i).getNome();
        }
        boxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(f));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManipularReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManipularReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManipularReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManipularReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManipularReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox<String> boxCliente;
    protected javax.swing.JComboBox<String> boxFuncionario;
    protected javax.swing.JComboBox<String> boxServico;
    protected javax.swing.JButton bttCancelar;
    protected javax.swing.JButton bttSalvar;
    protected datechooser.beans.DateChooserCombo choData;
    protected javax.swing.JLabel lblCliente;
    protected javax.swing.JLabel lblData;
    protected javax.swing.JLabel lblFuncionario;
    protected javax.swing.JLabel lblHorario;
    protected javax.swing.JLabel lblServico;
    protected javax.swing.JLabel lblTitulo;
    protected javax.swing.JList<String> lstHorario;
    protected javax.swing.JPanel pnlReserva;
    protected javax.swing.JScrollPane scrHorario;
    // End of variables declaration//GEN-END:variables
}
