/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Luiz Alberto Teodoro de Arruda
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblReserva = new javax.swing.JLabel();
        bttReserva = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        bttCliente = new javax.swing.JButton();
        lblFuncionario = new javax.swing.JLabel();
        bttFuncionario = new javax.swing.JButton();
        lblServico = new javax.swing.JLabel();
        bttServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EasyCut");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setName("cliente"); // NOI18N
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(400, 424));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logoEasyCut.png"))); // NOI18N

        lblReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/calendar32.png"))); // NOI18N

        bttReserva.setBackground(new java.awt.Color(102, 0, 153));
        bttReserva.setForeground(new java.awt.Color(255, 255, 255));
        bttReserva.setText("Gerenciar Reservas");
        bttReserva.setPreferredSize(new java.awt.Dimension(194, 32));
        bttReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReservaActionPerformed(evt);
            }
        });

        lblCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/group32.png"))); // NOI18N

        bttCliente.setBackground(new java.awt.Color(102, 0, 153));
        bttCliente.setForeground(new java.awt.Color(255, 255, 255));
        bttCliente.setText("Gerenciar Clientes");
        bttCliente.setPreferredSize(new java.awt.Dimension(194, 32));
        bttCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttClienteActionPerformed(evt);
            }
        });

        lblFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/workers32.png"))); // NOI18N

        bttFuncionario.setBackground(new java.awt.Color(102, 0, 153));
        bttFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        bttFuncionario.setText("Gerenciar Funcionários");
        bttFuncionario.setPreferredSize(new java.awt.Dimension(194, 32));
        bttFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttFuncionarioActionPerformed(evt);
            }
        });

        lblServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/hairdryer32.png"))); // NOI18N

        bttServico.setBackground(new java.awt.Color(102, 0, 153));
        bttServico.setForeground(new java.awt.Color(255, 255, 255));
        bttServico.setText("Gerenciar Serviços");
        bttServico.setPreferredSize(new java.awt.Dimension(194, 32));
        bttServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReserva, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblServico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblLogo)
                .addGap(36, 36, 36)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReserva)
                    .addComponent(bttReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionario))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblServico)
                    .addComponent(bttServico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReservaActionPerformed
        GerenciarReservas reservas = new GerenciarReservas();
        reservas.show();
    }//GEN-LAST:event_bttReservaActionPerformed

    private void bttClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteActionPerformed
        GerenciarClientes clientes = new GerenciarClientes();
        clientes.show();
        clientes.inflateTable();
    }//GEN-LAST:event_bttClienteActionPerformed

    private void bttFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttFuncionarioActionPerformed
        GerenciarFuncionarios funcionarios = new GerenciarFuncionarios();
        funcionarios.show();
        funcionarios.inflateTable();
    }//GEN-LAST:event_bttFuncionarioActionPerformed

    private void bttServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttServicoActionPerformed
        GerenciarServicos servicos = new GerenciarServicos();
        servicos.show();
        servicos.inflateTable();
    }//GEN-LAST:event_bttServicoActionPerformed
    
    /*protected void disableButtons(boolean disable) {
        bttReserva.setEnabled(!disable);
        bttCliente.setEnabled(!disable);
        bttFuncionario.setEnabled(!disable);
        bttServico.setEnabled(!disable);
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bttCliente;
    protected javax.swing.JButton bttFuncionario;
    protected javax.swing.JButton bttReserva;
    protected javax.swing.JButton bttServico;
    protected javax.swing.JLabel lblCliente;
    protected javax.swing.JLabel lblFuncionario;
    protected javax.swing.JLabel lblLogo;
    protected javax.swing.JLabel lblReserva;
    protected javax.swing.JLabel lblServico;
    protected javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
